xapi-project/xcp-rrdd

- rrdd/rrdd_server.ml
- rrdd/xcp_rrdd.ml
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>
> CA-126384: Use the new global ref for plugin_default

- rrdd/test_rrdd_monitor.ml
Theses changes make the tests much stronger and improve debug output when they fail.
CA-177649.
> Check actual datasource values rather than just list lengths

- rrdd/rrdd_monitor.ml
- rrdd/rrdd_shared.ml
- rrdd/test_rrdd_monitor.ml
- rrdd/xcp_rrdd.ml
Work in progress - please review for functionality, but not style!  I have a set of changes to refactor the updating code and remove the horrible amount of copy-pasta, but I need to strengthen the tests substantially to be sure I haven't broken anything.
> CP-13255: Update monitor to aggregate statistics for SR-level RRDs

- rrdd/rrdd_server.ml
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>
> CP-13481: Add SR level RRD APIs to the xcp-rrdd

- rrdd/rrdd_server.ml
- rrdd/rrdd_shared.ml
- rrdd/test_rrdd_monitor.ml
Note, this depends on https://github.com/xapi-project/xcp-idl/pull/100.
> CA-185923: Don't silently fail if archiving SR RRDs fails

- rrdd/xcp_rrdd.ml
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>
> CA-191570: Make use of meaningful tokens for xenstore watch

- rrdd/rrdd_stats.ml
RRDD used to call pidof to find the processes it was monitoring.
This imposed a slight extra load in dom0, and if a particular
process was not running pidof would fail and RRDD would log the
failure, causing lots of spurious logging.
Now we get the pids from pidfiles, and handle a missing pidfile
silently.
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> CA-201099: Read PIDs from pidfiles, rather than calling pidof

- rrdd/rrdd_common.ml
- rrdd/rrdd_fake.ml
- rrdd/rrdd_fake_common.ml
- rrdd/rrdd_ha_stats.ml
- rrdd/rrdd_http_handler.ml
- rrdd/rrdd_monitor.ml
- rrdd/rrdd_server.ml
- rrdd/rrdd_shared.ml
- rrdd/rrdd_stats.ml
- rrdd/xcp_rrdd.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Use packed stdext

- rrdd/rrdd_server.ml
This commit avoids logging the same error twice by introducing a "mute"
flag which is raised after a read error. It is taken down after the next
successful read.
This has been tested on a DT box and has substantially lowered the logging from xcp-rrdd:
```
2016-09-10 14:09:27   180 lines   300 sec    36.00/min #####
2016-09-10 14:14:28   180 lines   301 sec    35.88/min #####
2016-09-10 14:19:40   112 lines   312 sec    21.54/min ####
2016-09-10 14:25:21    36 lines   341 sec     6.33/min ##
2016-09-10 14:30:21    35 lines   300 sec     7.00/min ##
2016-09-10 14:35:22    35 lines   301 sec     6.98/min ##
2016-09-10 14:40:22    35 lines   300 sec     7.00/min ##
2016-09-10 14:46:21    17 lines   359 sec     2.84/min #
```
> CA-224730 mute plugin after read error, unmute after next succ. read

- rrdd/rrdd_server.ml
This commit introduces a skip count for plugins. After a read error, the
skip count is incremented and the plugin is not read for that number of
read cycles. When reading succeeds, the skip is reset to 0. Currently,
at most 256 cycles are skipped and the skip count increases
exponentially from 1 with every read error.
> CA-224730 back off exponentially after failed read from plugin

- rrdd/rrdd_bindings.ml
- rrdd/rrdd_server.ml
- rrdd/xcp_rrdd.ml
Updated @jonludlam's [PR](https://github.com/xapi-project/xcp-rrdd/pull/81) with requested changes.
> CP-26583: Update with PPX-based RRDD changes

- rrdd/rrdd_http_handler.ml
- rrdd/xcp_rrdd.ml
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> rrdd: make safe-strings compliant

- rrdd/rrdd_bindings.ml
- rrdd/xcp_rrdd.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> New ocaml-rpc

- rrdd/xcp_rrdd.ml
This adds a thread that logs memory statistics every 3 minutes. We can't
use OCAMLRUNPARAM parameter "v" because stderr is bound to /dev/null -
this would have been easier and less intrusive.
> XSI-283 add GC logging

- rrdd/xcp_rrdd.ml
This is a workaround for Xen's rare, unintentional leakage of a flag embedded into vcputime values that produces negative values for us.
The bitmask leaves usual values untouched while removing the incorrectly-set bit in malformed values.
> Fix incoming malformed vcputime values

- rrdd/xcp_rrdd.ml
Cherry-picked from #102 with conflicts resolved.
> Backport of CA-327028 for 1.9-lcm

- rrdd/xcp_rrdd.ml
Cherry-picked from #102 with conflicts resolved.
> Backport of CA-327028 for 1.14-lcm

- rrdd/rrdd_server.ml
Fixes f5169c9d83914d419a2884e2261caf6476bd82ce.
That commit improved the output of
query_possible_dss by attempting to report all
rrds, but it missed some. We fix that here - it
involves merging datasources from multiple places.
Signed-off-by: lippirk <ben.anson@citrix.com>
> CA-325582 fix bug with query_possible_dss

- lib/stats.ml
- rrdd/dune
- rrdd/rrdd_ha_stats.ml
- rrdd/rrdd_http_handler.ml
- rrdd/rrdd_monitor.ml
- rrdd/rrdd_server.ml
- rrdd/xcp_rrdd.ml
- xapi-rrdd.opam
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> CP-33121: stop using stdext's std and monadic modules

- rrdd/xcp_rrdd.ml
Logic was flipped with the last change
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> CA-338809: Update information for running VMs, not paused ones

- .ocamlformat
- Makefile
- dune-project
- lib/constants.ml
- lib/stats.ml
- lib/stats.mli
- rrdd/rrdd_bindings.ml
- rrdd/rrdd_common.ml
- rrdd/rrdd_fist.ml
- rrdd/rrdd_ha_stats.ml
- rrdd/rrdd_http_handler.ml
- rrdd/rrdd_monitor.ml
- rrdd/rrdd_server.ml
- rrdd/rrdd_shared.ml
- rrdd/rrdd_stats.ml
- rrdd/xcp_rrdd.ml
- rrddump/rrddump.ml
- test/test_rrdd_monitor.ml
Same format parameters as the others, some commented-out debug code was removed as well.
Please merge after https://github.com/xapi-project/xcp-rrdd/pull/115
> Format ocaml code using ocamlformat

- .travis.yml
- test/rrdd/dune
- test/transport/dune
By define packages for test binaries in the dune files.
> Test rrd-transport package and fix it

- Makefile
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
> Install rrddump
