rrdd/rrdd_monitor.ml

Otherwise the time since last update will be calculated as zero and the
datasources will be clobbered since gauge datasource types are multiplied by
the interval and so the datasource becomes zero.
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

CA-182722: Update RRDs only once per SR

---

rrdd/rrdd_server.ml
rrdd/rrdd_shared.ml

This PR is just for review, It need to be merged into trunk-thin-lvhd-2 branch.

CP-13995: Adding functions into xcp-rrdd for archiving of sr-level rrds

---

rrdd/rrdd_server.ml

We don't need this for the VM/host API calls as there's always
_some_ data sources for those objects, whereas for all SRs there
are currently none.
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

CA-197077: Handle there being no SR data sources.

---

rrdd/rrdd_server.ml

Unlocking a just unlocked mutex is an undefined behaviour. Its safety
completely depends on some compilation flags.
This commit adds the missing lock and introduces two newlines to
separate logical blocks of code.
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

Fix mutex-related undefined behaviour

---

rrdd/xcp_rrdd.ml

CA-277850 (failure to receive updates about free memory) is hard to
reproduce. We need at least temporarily more logging. This commit can be
reversed, once the problem has been fixed.

CA-277850 increase loglevel to info for memfree

---

rrdd/jbuild
rrdd/xcp_rrdd.ml
xapi-rrdd.opam

This commit replaces the use of xapi-xenops with ezxenstore. The latter
provides a more recent implementation to watch xenstore events. This
requires some small changes as the API between the two is slightly
different.
We suspect that issue CA-277850 is caused by the outdated xenstore watch
implementation.

CA-277850 Replace xenops library with ezxenstore

---

rrdd/xcp_rrdd.ml
xapi-rrdd.opam

This depends on xs-opam 4.1.0 being released and xapi-project/stdext#31 to be merged

update and simplify interface using fd-send-recv >= 2.0.0

---

lib/stats.ml
rrdd/rrdd_monitor.ml
rrdd/rrdd_server.ml
rrdd/rrdd_stats.ml
rrdd/xcp_rrdd.ml

This will allow xapi to read memory stats from the filesystem instead of depending directly on Xenctrl libs

CP-30614: Export Memory stats to filesystem

---

lib/stats.ml
rrdd/rrdd_monitor.ml
rrdd/rrdd_server.ml
rrdd/rrdd_stats.ml
rrdd/xcp_rrdd.ml

This reverts the commits below:
89e2eac9 2019-03-13 CP-30614: Do not register self-written files
badc7aa9 2019-03-13 maintenance: remove all Opens from xcp_rrdd
2176dc40 2019-03-13 maintenance: code reordering
6a574ec8 2019-03-13 CP-30614: Rename written DSS files
e6405ea0 2019-03-13 CP-30614: prefix files for easier identification
df51db12 2019-03-13 CP-30614: Write files for memory stats
3faf2e28 2019-03-13 CP-30614: Incorporate RRD filewriters
f482edc7 2019-03-13 maintenance: prepare for cleanup on sigint
a1848612 2019-03-13 maintenance: do not open Listext
88de8dd3 2019-03-13 CP-30614: decouple stats generation from consolidation
b970f84a 2019-03-13 maintenance: separate dds function naming from applicat
ca87ee8d 2019-03-13 maintenance: make update_loadavg to return a list of ds …

Revert merge psafont/CA-30614

---

lib/stats.ml
rrdd/rrdd_monitor.ml
rrdd/rrdd_server.ml
rrdd/rrdd_stats.ml
rrdd/xcp_rrdd.ml

Now we allocate 256 pages (1 MiB) to be able to accommodate stats for a 1000 VMs.
Most of the space used is for the json-like serialization metadata of the stats, clocking at a maximum of 620 bytes per VM, 1024 per VM should be enough (tests pending)

CP-30614: Export Memory stats to filesystem, again

---

rrdd/xcp_rrdd.ml

Discovered while investigating CA-322045 (xcp-rrdd takes a long time to finish backing up the rrds during a toolstack restart).
XAPI already enables this by default, so it should be safe to enable it
for xcp-rrdd too.
By default without fastpath Http_svr reads the http headers
byte-by-byte.
With fastpath it reads the minimum HTTP header request size, and then 4
byte at a time until end of headers (it still needs to stop exactly
where the headers finish so that file descriptor passing would work).
It might be possible to improve this further, since AFAICT xcp-rrdd does
not use file descriptor passing on its main socket, but perhaps
we could do that by switching to message-switch or cohttp in the future.
I've confirmed with `strace` that indeed xcp-rrdd reads requests more efficiently now: …

CA-322045: Enable fastpath for xcp-rrdd http server

---

rrdd/rrdd_server.ml
rrdd/xcp_rrdd.ml

These are files in `/dev/shm/metrics` created by tapdisk, but they are not in the right format.
We actually use xcp-rrdp-iostat which looks for metrics in `/dev/shm/td*` instead, so avoid spamming the logs.
@lippirk this might be useful for the issue you are working on too.
Also there was a place where we logged these messages while holding a lock, it should be safe to log this outside the lock.

CA-322045: do not spam the logs with errors about the 'tap-%d-%d' plugins

---

rrdd/rrdd_server.ml
rrdd/xcp_rrdd.ml

Had to use Xstringext instead of Astring (astring is present but would require updating the _oasis file which would regenerate setup.ml containing a lot of changes) to make backport simpler.

CA-322045: backport

---

rrdd/rrdd_server.ml

Previously only active (enabled) datasources were being exposed through the API. This means that now xen-api has visibility all default datasources, which translate in all datasources in practice.
This is necessary for xapi to clean up datasources when destroying SRs.
Unfortunately inactive sources do not have available neither the metrics nor the description. This is because there are 3 "datasource" types scattered in the system, 2 of them in the same data structure in xcp-rrdd. I think it would be beneficial if these were consolidated somehow to remove duplication.
From the 3 commits, only one is needed to report disabled datasources, the other two help keep the memory consumption down.

CA-325582: Report disabled datasources

---

rrdd/rrdd_server.ml

Previously they weren't being reported at all, which made it impossible
for xapi to have visibility on them.
(This is a combination of 46219b8
and b0af2ca. There was a bug with
the former, which is fixed by the latter. Only the latter is
cherry-picked to avoid extra work.)
Signed-off-by: lippirk <ben.anson@citrix.com>
(cherry picked from commit b0af2ca)

CA-325582 Report disabled data sources (backport to 7.1 CU2)

---

.travis.yml
rrdd/rrdd_server.ml

They are used to enable collection of stats, as it might be disabled by
default.
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>

rrdd_server: document add functions

---

rrdd/xcp_rrdd.ml

Depends on https://github.com/xapi-project/xenopsd/pull/708

CA-335964: Actively mask temporary VM UUIDs from exposed metrics

---

rrdd/rrdd_server.ml
rrdd/xcp_rrdd.ml

There were two other functions where they could have leaked from.
uuid_of_domid was moved to be an internal function since it should be
avoided whenever possible. It's needed here since the origin of the
domid are the stats and not the list of domain metadata.

CA-335964: Do not expose temporary VM UUIDs

---

bin/rrdd/rrdd_server.ml
bin/rrdd/rrdd_shared.ml

We use a placeholder of None in the send_rrd function. This should be
changed later to use the special migration trust bundle.

CP-36100 REQ-403 add verify_cert parameter to SSL make calls

---

Makefile
bin/rrdd/rrdd_server.ml

They are used for sending rrds to the pool master exclusively by xapi,
and it has no way to send them to any other host. Connecting to hosts
outside of the pool and verification must fail in these cases.
This deductions were done thanks to https://github.com/xapi-project/xen-api/pull/4358

CP-36100: verify remote host on rrd backup and archive
